# Generated by Django 5.1.2 on 2024-11-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_remove_receta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.AddField(
            model_name='receta',
            name='pasos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
