# Generated by Django 5.1.2 on 2024-11-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0003_receta_foto_receta_pasos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='foto',
        ),
    ]
